frase = input('Digite uma frase:').title().strip()
FRASE = frase.upper()
f = FRASE.split()
F = ''.join(f)
print('Frase analisada: ', frase)
print('A frase tem {} letras.'.format(len(F)))
print("""A letra "A" aparece na frase {} vezes""".format(FRASE.count('A')))
print("""A primeira letra "A" é a {}º letra da frase.""".format(F.find('A')+1))
print("""A última letra "A" é a {}º letra da frase.""".format(F.rfind('A')+1))
